sudo: false  # Use container-based infrastructure
language: python
python:
  - "2.7"
  - "3.6"
before_install:
  # Commands below copied from: http://conda.pydata.org/docs/travis.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # reset the shell's lookup table for program name to path mappings
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
install:
  - >
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
      nose pylint pandoc
  - source activate test-environment
  - pip install pypandoc
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
script:
  - ./lint.sh
  - nosetests test --verbose --with-coverage --cover-package=serializable
after_success:
  coveralls
deploy:
  provider: pypi
  distributions: sdist
  user: hammerlab
  password:
    secure: "voln0SA6GaJ+sxnI3BYCz2yWXy0YWQ9YKmeB8nXtCTnBMZoE+FxiNDuJ6winoRPqub0BE+x8cyxkADOm0gwnRwSMPpIIasNMEw3R1SH2DBTOX5j0p+qDagQhlf9dPBMA2iDCO/NCfXbucdxk7aeB/o4Wwc1P4OEImKyp1ecbggC+TwMtBtiZZSPNgpJvTpll29Ae0YFe73/j3KdLrKrstXBvT79YRe8GKeujvdeeXakZtMqEE2Lnap1YI98UGfjUDxiF6gE8JG9QHi2r5WRB+jOv8qly8QTdB/8Dq5Ybz67Ndx2rnKK2VM2GCQ6Tk8rNP8c7Kxp0uTylVe1TRKxhfpCw4yr3pmoNOkVI71oqYYX27J2LiDsI68SQtjz/TcgbNq61j6hZC2DYqzFjZ3z9iZLVqbiMjMgNntlAqURsXulVSuo/oul7Ui7p3VRu/fqjw1hlelmOdUvlMXTOOhh2xcW6S7tGbNf8GSjlNs9nwOZQquqAl9HTjNdQU+438GhNDf3GkwpkM+RiQoulzoPoY/+NcGCIg5v2/rXkwG8uqmKBqCYFFHjsmYpK0ndEi8EhmAhb4WGAPYSFaNJChCQTAFQrNiGOW3xu41R9W4jM/4RZvpjVjWAG/QJPADJEkFyA4gL+w/9Cn+k3SkRmWq9nMFgyufRQT0aTh/EwKO1hObs="
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "2.7"

